server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass web_php:9000; # Asegúrate de que el servicio PHP en Docker se llama "web_php"
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Configuración del error 404 personalizado
    error_page 404 /404.html;
    
    location = /404.html {
        root /var/www/html;
        internal; # Evita que los usuarios accedan directamente a 404.html
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
